import re
from deep_translator import GoogleTranslator

def translate_markdown(content):
    # Regex to identify code blocks (fenced with ```) and inline code (backticks)
    # We want to avoid translating content inside ``` ... ```
    
    # Split by code blocks
    parts = re.split(r'(```[\s\S]*?```)', content)
    translated_parts = []
    
    translator = GoogleTranslator(source='fr', target='en')
    
    for part in parts:
        if part.startswith('```'):
            # It's a code block, keep as is
            translated_parts.append(part)
        else:
            # It's text (or inline code). 
            # Translating the whole chunk might lose newlines or formatting.
            # Let's split by lines to be safer with structure? 
            # No, context is better preserved with paragraphs.
            # Let's try translating the chunk.
            if part.strip():
                try:
                    # Translate
                    translated = translator.translate(part)
                    # Restore some markdown specific things if broken?
                    # For now, trust the translator
                    translated_parts.append(translated)
                except Exception as e:
                    print(f"Translation error: {e}")
                    translated_parts.append(part)
            else:
                translated_parts.append(part)
                
    return ''.join(translated_parts)

def main():
    try:
        with open('README.md', 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Add header indicating it's auto-generated
        header = "<!-- This file is auto-generated by a GitHub Action. Do not edit manually. -->\n\n"
        
        translated_content = translate_markdown(content)
        
        with open('README_EN.md', 'w', encoding='utf-8') as f:
            f.write(header + translated_content)
            
        print("Successfully generated README_EN.md")
        
    except Exception as e:
        print(f"Error: {e}")
        exit(1)

if __name__ == "__main__":
    main()
